# Generated by Django 4.2.1 on 2023-05-15 20:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('confirm_password', models.CharField()),
                ('bio', models.TextField()),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('skills_strong', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, choices=[('HTML', 'Hypertext Markup Language'), ('CSS', 'Cascade Style Sheets'), ('JS', 'Javascript')], size=None)),
                ('skills_weak', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, choices=[('HTML', 'Hypertext Markup Language'), ('CSS', 'Cascade Style Sheets'), ('JS', 'Javascript')], size=None)),
                ('profile_pic', models.ImageField(default='https://imgur.com/a/2L57GM9', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='GA_Tea.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='GA_Tea.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('likes', models.IntegerField()),
                ('pic', models.ImageField(blank=True, upload_to='')),
                ('timeline', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='GA_Tea.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='GA_Tea.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='GA_Tea.user'),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interviewed', 'Interviewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Interested', 'Interested')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='GA_Tea.user')),
            ],
        ),
    ]
