# Generated by Django 4.2.1 on 2023-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_Tea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='github',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='linkedin',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='pic',
            field=models.CharField(default='https://imgur.com/a/2L57GM9'),
        ),
    ]
