# Generated by Django 4.2.1 on 2023-05-17 00:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_Tea', '0002_remove_post_likes_alter_post_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='GA_Tea.hashtag'),
        ),
    ]
