# Generated by Django 4.2.1 on 2023-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_Tea', '0003_alter_post_skills_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pic',
            field=models.CharField(default='https://i.imgur.com/RMiSvIF.png'),
        ),
    ]
