# Generated by Django 4.2.1 on 2023-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_Tea', '0004_alter_account_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pic',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/en/2/2d/SSU_Kirby_artwork.png'),
        ),
    ]
