# Generated by Django 4.2.1 on 2023-05-15 21:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_Tea', '0006_alter_post_skills_req_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='skills_req',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, choices=[('HTML', 'HyperText Markup Language'), ('CSS', 'Cascading Style Sheets'), ('JS', 'JavaScript'), ('React', 'React'), ('Next.js', 'Next.js'), ('Mongo', 'Mongo'), ('Express', 'Express'), ('Postgres', 'PostgreSQL'), ('Python', 'Python'), ('Django', 'Django'), ('Node', 'Node.js'), ('REST', 'REpresentational State Transfer'), ('Web APIs', 'Web APIs'), ('Git', 'Git'), ('Data Structures and Algorithms', 'Data Structures and Algorithms')], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills_strong',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, choices=[('HTML', 'HyperText Markup Language'), ('CSS', 'Cascading Style Sheets'), ('JS', 'JavaScript'), ('React', 'React'), ('Next.js', 'Next.js'), ('Mongo', 'Mongo'), ('Express', 'Express'), ('Postgres', 'PostgreSQL'), ('Python', 'Python'), ('Django', 'Django'), ('Node', 'Node.js'), ('REST', 'REpresentational State Transfer'), ('Web APIs', 'Web APIs'), ('Git', 'Git'), ('Data Structures and Algorithms', 'Data Structures and Algorithms')], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills_weak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, choices=[('HTML', 'HyperText Markup Language'), ('CSS', 'Cascading Style Sheets'), ('JS', 'JavaScript'), ('React', 'React'), ('Next.js', 'Next.js'), ('Mongo', 'Mongo'), ('Express', 'Express'), ('Postgres', 'PostgreSQL'), ('Python', 'Python'), ('Django', 'Django'), ('Node', 'Node.js'), ('REST', 'REpresentational State Transfer'), ('Web APIs', 'Web APIs'), ('Git', 'Git'), ('Data Structures and Algorithms', 'Data Structures and Algorithms')], null=True, size=None),
        ),
    ]
