# Generated by Django 4.2.1 on 2023-05-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GA_Tea', '0007_alter_post_skills_req_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
